name: action-semver
description: Versioning based on latest GitHub Release tag in SemVer format and using Conventional Commits to determine the next version

author: CDQ AG
branding:
  icon: 'star'
  color: 'green'

inputs:
  github-token:
    description: GitHub Token
    required: true

  target-branch:
    description: The branch to use when fetching list of commits to compare against
    default: master

  not-conventional-commits-reaction:
    description: 'Whether to exit with an error, warning or silently when encountering a commit that does not follow conventional commit format. Available options: error, warn, silent'
    default: warn

  init-release-version:
    description: Initial version to use when no release tags are found in the repository
    default: v0.1.0

outputs:
  latest-release-tag:
    description: 'Latest release tag found in the repository'

  current-version:
    description: 'Current version in format x.y.z'

  new-version:
    description: 'New version in format x.y.z'

  new-major-version:
    description: 'New major version'

runs:
  using: node20
  main: dist/index.js
